### ISSUE TITLE
Doesn't work with Denite?

### ISSUE THREAD

**Issue by Axioplase** [Shougo/tabpagebuffer.vim#1]
Hi,

I've installed both Denite and tabpagebuffer.vim, but tabpagebuffer doesn't seem to work.
```
:Denite <tab>
```
shows
```
base buffer change colorscheme ...
```
Do I need to do any specific setup? [This comment](https://vi.stackexchange.com/a/4231) made me believe it would work out of the box...

**Comment by Shougo** [comment]
Yes.  It is feature.
You should read the comment carefully.
It says about unite.vim instead of denite.

**Comment by Shougo** [comment]
I use `file/old` source and `matcher/project_files` for it.

```vim
call denite#custom#source('file/old', 'matchers',
      \ ['matcher/fuzzy', 'matcher/project_files'])
```

**Comment by Shougo** [comment]
It may be work.

```vim
call denite#custom#source('buffer', 'matchers',
      \ ['matcher/fuzzy', 'matcher/project_files'])
```
